export const APP_NAME = "Fluxor";

export const DEFAULT_SERVICE_FEE_PERCENT = 10;

export const TABLE_STATUS = {
  FREE: "FREE",
  OCCUPIED: "OCCUPIED",
  WAITING_SERVICE: "WAITING_SERVICE",
  WAITING_PAYMENT: "WAITING_PAYMENT",
  BLOCKED: "BLOCKED",
} as const;

export const TICKET_STATUS = {
  OPEN: "OPEN",
  IN_PROGRESS: "IN_PROGRESS",
  WAITING_PAYMENT: "WAITING_PAYMENT",
  PAID: "PAID",
  CANCELED: "CANCELED",
} as const;

export const SUBSCRIPTION_STATUS = {
  TRIALING: "TRIALING",
  ACTIVE: "ACTIVE",
  COURTESY: "COURTESY",
  PAST_DUE: "PAST_DUE",
  SUSPENDED: "SUSPENDED",
  CANCELED: "CANCELED",
  EXPIRED: "EXPIRED",
} as const;